---
# Install Redis server
- name: "Install Redis server: ${redis.package}"
  apt: pkg=${redis.package} state=installed update-cache=yes
  tags:
    - redis

# Bind Redis server to all interfaces
- name: "Bind Redis server to all interfaces"
  lineinfile: dest=/etc/redis/redis.conf state=present regexp="^#?bind" line="#bind 127.0.0.1"
  tags:
    - redis

# Ensure Redis server is running
- name: "Ensure Redis server is running"
  service: name=${redis.package} state=started
  tags:
    - redis